### ISSUE TITLE
Logging Output is Missing the Sceptre Stack Name Prefix

### ISSUE THREAD

**Issue by X-Guardian** [Sceptre/sceptre-cdk-handler#9]
### Subject of the issue

Log messages produced by the handler are missing the Sceptre stack name prefix.

### Your environment

- `sceptre-cdk-handler v1.0.0`

### Steps to reproduce

`sceptre launch cdk.yaml`

### Expected behaviour

```
[2023-01-05 12:43:50] - cdk - Launching Stack
[2023-01-05 12:43:51] - cdk - Stack is in the CREATE_COMPLETE state
[2023-01-05 12:43:51] - cdk - Updating Stack
sceptre-example@ C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\sceptre-example
└── (empty)

C:\Program Files\nodejs -> .\
└── cdk-assets@2.59.0

[2023-01-05 12:44:14] - cdk - Publishing CDK assets
...
```

### Actual behaviour

```
[2023-01-05 12:43:50] - cdk - Launching Stack
[2023-01-05 12:43:51] - cdk - Stack is in the CREATE_COMPLETE state
[2023-01-05 12:43:51] - cdk - Updating Stack
sceptre-example@ C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\sceptre-example
└── (empty)

C:\Program Files\nodejs -> .\
└── cdk-assets@2.59.0

[2023-01-05 12:44:14] - Publishing CDK assets
...
```

Note the missing `cdk` prefix on the `Publishing CDK assets` log message.

### Resolution

Restore the `PrefixLoggerAdapter` code that was removed in PR #3.

**Comment by jfalkenstein** [comment]
Hey, thanks for raising this issue. I see your point in that logs out of template handlers aren't prefixed with the appropriate stack name. However, I don't think that an individual template handler should actually address this issue. Instead, I think this really ought to be an issue on Sceptre itself. Since Sceptre is the one that sets up the logger and passes it to template handlers, hooks, and resolvers, I think that within _Sceptre_ is the appropriate place to apply the stack name on the logger handed to these extensions. If we do it there, we won't essentially have to apply the same logic all over the place.

As such, I'm going to close this Issue here and open an issue on the Sceptre repo to resolve the issue there.

**Comment by jfalkenstein** [comment]
Issue created here: https://github.com/Sceptre/sceptre/issues/1304
